# How GitHub renders the "Sponsor" button for Quipu.
# - github:          GitHub Sponsors profile(s). Requires enrolling at
#                    https://github.com/sponsors (identity + payout setup).
# - open_collective: the collective slug -> https://opencollective.com/quipu
#                    Create it with fiscal host "Open Source Collective" to
#                    accept corporate/invoiced funding transparently.
# Donations are a complement; the core revenue is the commercial license and
# the VOPRF SaaS. Prefer org/sponsorship tiers over "tip" tiers.
github: [isazajuancarlos]
open_collective: quipu
