#ifndef QUIPU_H
#define QUIPU_H

/* Generated by cbindgen from quipu-capi. Do not edit by hand. Regenerate: cd bindings/c && cbindgen --config cbindgen.toml --crate quipu-capi --output include/quipu.h */

#include <stdint.h>
#include <stddef.h>

// Status codes returned by every fallible export. `0` = success, negative =
// error. Coarse by design: no failure oracle finer than the Rust API's.
enum quipu_status
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    QUIPU_OK = 0,
    QUIPU_ERR_NULL_ARG = -1,
    QUIPU_ERR_AUTH = -2,
    QUIPU_ERR_KEY = -3,
    QUIPU_ERR_CHUNK = -4,
    QUIPU_ERR_INTERNAL = -5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum quipu_status quipu_status;
#else
typedef int32_t quipu_status;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns a static, NUL-terminated version string. DO NOT free.
const char *quipu_version(void);

// Frees a byte buffer returned by any `quipu_*` function. The buffer is wiped
// before release, so secret keys and decrypted plaintext leave no residue. No-op
// on NULL.
//
// # Safety
// `ptr`/`len` must come unmodified from a Quipu byte output, freed once.
void quipu_bytes_free(uint8_t *ptr, uintptr_t len);

// Encrypts `data` into the streaming AEAD container (`QST1`). `chunk_size == 0`
// uses the format default; otherwise it must be in 4 KiB..=16 MiB. `pepper`
// may be `(NULL, 0)`.
//
// # Safety
// Pointers must satisfy the documented borrow/out-pointer contracts.
int32_t quipu_encrypt_stream(const uint8_t *data,
                             uintptr_t data_len,
                             const char *passphrase,
                             const uint8_t *pepper,
                             uintptr_t pepper_len,
                             uintptr_t chunk_size,
                             uint8_t **out,
                             uintptr_t *out_len);

// Decrypts a `QST1` container produced by `quipu_encrypt_stream` (same
// `pepper`). `chunk_size` is read from the header.
//
// # Safety
// Pointers must satisfy the documented borrow/out-pointer contracts.
int32_t quipu_decrypt_stream(const uint8_t *blob,
                             uintptr_t blob_len,
                             const char *passphrase,
                             const uint8_t *pepper,
                             uintptr_t pepper_len,
                             uint8_t **out,
                             uintptr_t *out_len);

// Frees a string returned by any `quipu_*` function. No-op on NULL.
//
// # Safety
// `ptr` must come unmodified from a Quipu string output, freed once.
void quipu_string_free(char *ptr);

// Encodes `data` protected by `passphrase` into glyph symbols. `pepper` may be
// `(NULL, 0)`. On success writes a NUL-terminated string to `*out`.
//
// # Safety
// Pointers must satisfy the documented borrow/out-pointer contracts.
int32_t quipu_encode(const uint8_t *data,
                     uintptr_t data_len,
                     const char *passphrase,
                     const uint8_t *pepper,
                     uintptr_t pepper_len,
                     char **out);

// Decodes glyph `symbols` with `passphrase` (and optional `pepper`). On success
// writes plaintext bytes to `*out`/`*out_len`.
//
// # Safety
// Pointers must satisfy the documented borrow/out-pointer contracts.
int32_t quipu_decode(const char *symbols,
                     const char *passphrase,
                     const uint8_t *pepper,
                     uintptr_t pepper_len,
                     uint8_t **out,
                     uintptr_t *out_len);

// Generates a hybrid post-quantum keypair (X25519 + ML-KEM-1024). Writes the
// public key (1600 B) and secret key (3200 B) as freshly allocated buffers.
//
// # Safety
// All four out-pointers must be valid, writable pointers.
int32_t quipu_generate_keypair(uint8_t **pk, uintptr_t *pk_len, uint8_t **sk, uintptr_t *sk_len);

// Encrypts `data` to a recipient's hybrid public key (`pk`, 1600 B). On success
// writes glyph symbols to `*out`.
//
// # Safety
// Pointers must satisfy the documented borrow/out-pointer contracts.
int32_t quipu_encrypt_to_recipient(const uint8_t *data,
                                   uintptr_t data_len,
                                   const uint8_t *pk,
                                   uintptr_t pk_len,
                                   char **out);

// Decrypts recipient symbols with the hybrid secret key (`sk`, 3200 B). On
// success writes plaintext to `*out`/`*out_len`.
//
// # Safety
// Pointers must satisfy the documented borrow/out-pointer contracts.
int32_t quipu_decrypt_as_recipient(const char *symbols,
                                   const uint8_t *sk,
                                   uintptr_t sk_len,
                                   uint8_t **out,
                                   uintptr_t *out_len);

// Generates a hybrid signing keypair (Ed25519 + ML-DSA-87). Writes the
// verifying key (2624 B) and the sensitive signing key (64 B).
//
// # Safety
// All four out-pointers must be valid, writable pointers.
int32_t quipu_generate_signing_keypair(uint8_t **vk,
                                       uintptr_t *vk_len,
                                       uint8_t **sk,
                                       uintptr_t *sk_len);

// Signs `data` with the hybrid signing key (`sk`, 64 B). The output is a
// self-contained, SIGNED-BUT-CLEARTEXT artifact (authenticity, not secrecy).
// On success writes glyph symbols to `*out`.
//
// # Safety
// Pointers must satisfy the documented borrow/out-pointer contracts.
int32_t quipu_sign(const uint8_t *data,
                   uintptr_t data_len,
                   const uint8_t *sk,
                   uintptr_t sk_len,
                   char **out);

// Verifies a signed artifact against the PINNED verifying key (`vk`, 2624 B)
// and, only if it validates, writes the message to `*out`/`*out_len`.
//
// # Safety
// Pointers must satisfy the documented borrow/out-pointer contracts.
int32_t quipu_verify(const char *symbols,
                     const uint8_t *vk,
                     uintptr_t vk_len,
                     uint8_t **out,
                     uintptr_t *out_len);

// Client-side VOPRF blinding. Writes the ephemeral blind state (64 B, KEEP for
// finalize) and the blinded point (32 B, SEND to the server). Both buffers are
// freshly allocated; free with `quipu_bytes_free`.
//
// # Safety
// All four out-pointers must be valid, writable pointers.
int32_t quipu_voprf_blind(const uint8_t *password,
                          uintptr_t password_len,
                          uint8_t **state,
                          uintptr_t *state_len,
                          uint8_t **blinded,
                          uintptr_t *blinded_len);

// Client-side VOPRF finalize. VERIFIES the DLEQ `proof` (64 B) against the
// PINNED `server_pub` (32 B) and, only if it validates, writes the 64 B
// hardened secret to `*out`/`*out_len` (free with `quipu_bytes_free`).
// NOTE: 64 B, not 32 — RFC 9497's output is the full SHA-512 hash. This
// changed when the custom construction was replaced by the conformant one.
// `state` (64 B) is from `quipu_voprf_blind`; `evaluated` (32 B) and `proof`
// come from the server. Returns `QUIPU_ERR_AUTH` if the proof is invalid
// (dishonest server or wrong pinned key).
//
// # Safety
// Pointers must satisfy the documented borrow/out-pointer contracts.
int32_t quipu_voprf_finalize(const uint8_t *password,
                             uintptr_t password_len,
                             const uint8_t *state,
                             uintptr_t state_len,
                             const uint8_t *evaluated,
                             uintptr_t evaluated_len,
                             const uint8_t *proof,
                             uintptr_t proof_len,
                             const uint8_t *server_pub,
                             uintptr_t server_pub_len,
                             uint8_t **out,
                             uintptr_t *out_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* QUIPU_H */
